import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = "/tmp/archguard-quality-product-reporter-survivor-review";
const recordsDirectory = "/tmp/archguard-quality-product-self-profiles-final18/state/reporter/records";
const sourceRoot = "/tmp/archguard-quality-product-cli-reviewed-worktree";
const hash = bytes => crypto.createHash("sha256").update(bytes).digest("hex");
const useful = (reason, suggestedControl) => ({classification:"useful_missing_public_control",reason,suggestedControl});
const detail = reason => ({classification:"implementation_detail",reason,suggestedControl:null});
const equivalent = reason => ({classification:"equivalent",reason,suggestedControl:null});
const unresolved = reason => ({classification:"unresolved",reason,suggestedControl:null});

function classify(result) {
  const {line}=result.location;
  const before=result.context.before;
  if(line===39) return useful("The edit removes the first character of every nonempty error message, including short messages that require no truncation.","A failed assertion retains the exact short message, a corrected passing run has no failures.");
  if(line===40 && before.includes("slice")) return useful("Byte-budget trimming removes the message prefix as well as its suffix, which can remove the error's identifying text.","A long multibyte diagnostic retains its distinctive prefix, carries a truncation marker, and remains valid UTF-8.");
  if(line===40) return detail("The edit trims one additional character when a message occupies exactly the reporter's internal 4,000-byte limit. The published protocol permits bounded truncated messages and does not promise this private boundary.");
  if(line===41 || line===42 && result.operator!=="logical") return detail("The edit changes handling of a trailing unpaired high surrogate. Valid UTF-16 messages split at the 4,000-code-unit boundary already exceed the byte limit and the preceding byte loop removes that incomplete pair. Arbitrary malformed JavaScript strings can differ, so this is not a universal equivalence claim. The later UTF-8 conversion still produces valid protocol text.");
  if(line===42) return useful("The changed logical operator drops the final character of ordinary short messages because almost every character matches one side of the condition.","Require the exact short diagnostic and retain a clean passing control.");
  if(line===44) return useful("The edit marks unchanged short diagnostics as truncated.","Require the exact short diagnostic and check an actual long diagnostic still carries the truncation marker.");
  if(line===48) return useful("Node assertion name and code aliases become runtime failures, so a real test assertion no longer counts as assertion evidence.","Exercise both the AssertionError [ERR_ASSERTION] name and the ERR_ASSERTION code, with TypeError and passing controls.");
  if(line===64) return equivalent("For the public one-shot lifecycle, closeFinished can become true only inside closeBridge after closeStarted becomes true. Initializing closeStarted to true cannot make complete true while closeFinished remains false. No other public behavior reads closeStarted.");
  if(line===65) return useful("A close that started but never settled can be reported complete with no failures.","Start a close promise that remains pending, verify incomplete evidence, then verify a resolved close completes cleanly.");
  if(line===66 || line===112) return useful("Ordinary logger calls outside runner close become cleanup failure evidence.","Logger calls before and after a successful close leave a passing result complete and free of failures, while actual cleanup logging remains a runtime failure.");
  if(line===68) return detail("Before finalization, an uncaught exception triggers an extra publication attempt. The exit listener still finalizes again, and supported is already false with unhandled evidence. Counting intermediate writes would test the implementation rather than the final result contract.");
  if(line===70) return detail("Every accepted onTestRunEnd call overwrites interrupted from its reason. The changed initial value affects only an incomplete process that never ends a run, changing its incomplete reason without allowing completion.");
  if(line===78) return useful("The process accepts a second reporter and installs another set of finalization listeners.","A second reporter construction is rejected while the first reporter still publishes the valid one-shot result.");
  if(line===83) return useful("A late throwing exit listener without an assigned exit code can publish a status that disagrees with Node's actual termination, or force fallback metadata.","Run a clean test without assigning process.exitCode, then throw in a later exit listener. Require incomplete unhandled evidence and a result status matching the raw child status.");
  if(line===89 && result.operator==="comparison") return detail("The edit admits one failure beyond the shared wire ceiling. SDK validation rejects the oversized result and publishes the conservative fallback, so it does not turn the overflow into complete evidence. A test requiring the exact retained failure array would add a diagnostic retention requirement beyond the documented fallback.");
  if(line===89) return useful("Infrastructure failure overflow can leave the result marked complete while additional events were dropped.","Emit more than the shared failure budget during close, require incomplete evidence, and verify a single cleanup error remains separately recorded.");
  if(line===94 || line===95) return detail("The early API rejection changes, but a missing method still prevents settlement or successful close, fails the final API checks, or reaches the conservative publication fallback. These paths continue to publish incomplete evidence. Better early diagnostics are possible, but there is no demonstrated false complete result from this edit under one-shot usage.");
  if(line===129 && result.operator==="comparison") return useful("One hook event beyond the reporter's event budget is accepted, and an all-passing oversized hook inventory can remain complete.","Require an oversized hook event stream to remain incomplete, with a normal passing hook control.");
  if(line===129) return useful("An oversized hook event stream can retain a true supported flag after the reporter stops recording events.","Require oversized hook event metadata to remain incomplete, with a normal passing hook control.");
  if(line===136 && result.operator==="comparison") return detail("The edit rejects a boundary-sized input one event earlier. It reduces the accepted inventory limit and does not permit incomplete analysis to appear complete. The exact private event ceiling is not an adopter contract.");
  if(line===136 && result.operator==="logical" && before.includes("modules.length")) return useful("An oversized module inventory is accepted when the early error inventory stays within budget.","Use a finite oversized module inventory with one valid test and otherwise empty modules, require incomplete evidence, and preserve a normal passing module control.");
  if(line===136) return useful("A second onTestRunEnd call can escape the one-shot run guard and retain complete evidence.","End the same run twice, require incomplete evidence, and preserve a single-run passing control.");
  if(line===139) return useful("An unsupported run-end reason can remain complete.","Use an unknown run reason, require incomplete evidence, and retain passed, failed, and interrupted controls.");
  if(line===143) return detail("The immediate context or wait-method check changes, but no callback settlement is recorded on rejection and final collection rechecks the context methods. A replaced wait method still fails the final identity check. No useful public completion difference has been established.");
  if(line===147 && result.operator==="boolean") return equivalent("Returning from the invalid-promise branch leaves runSettled false. Its true supported assignment cannot satisfy the independent runSettled completion requirement in a one-shot run.");
  if(line===147) return detail("An invalid wait return value reaches the catch block instead of the early return, adding a runtime diagnostic. runSettled remains false in either case, so the run stays incomplete.");
  if(line===155) return useful("A runner cleanup timeout can publish complete:true if the child exits nonzero, even though timeout evidence is present.","Call onProcessTimeout after a settled failed run, require incomplete runtime evidence, and verify a corrected run completes.");
  if(line===163 || line===165 && result.operator==="comparison") return detail("The edit changes the exact internal aggregate event budget boundary by one event. It can reject a boundary-sized traversal earlier but does not permit a false complete result.");
  if(line===165 && result.expected==="*") return detail("The aggregate event budget becomes smaller. This rejects larger supported inventories earlier, but does not compromise conservative incomplete reporting. A workload-size acceptance promise would be needed to make the exact private capacity a useful public control.");
  if(line===165 && result.expected==="-") return useful("The available event budget grows with each visited event instead of decreasing, so the aggregate traversal bound stops enforcing a limit.","Use an oversized finite suite inventory, require incomplete evidence, and verify a normal suite inventory completes.");
  if(line===165 && before.endsWith("this.supported = ")) return useful("The module loop relies on reserve to mark budget exhaustion unsupported. After earlier suites and tests fill the aggregate budget, the next module can stop collection while leaving complete:true.","Use a finite mixed module and suite inventory that exceeds the aggregate event budget, require incomplete evidence, and keep a smaller complete inventory as the corrected control. The assertion targets completeness rather than an internal counter.");
  if(line===165) return detail("The reserve function still sets supported false on exhaustion, but returning true continues collection beyond that internal point. Completion remains conservative. This changes internal traversal work and needs a separate bounded-iteration requirement before adding a public behavior assertion.");
  if(line===170 && result.operator==="comparison") return detail("One failure beyond the wire ceiling reaches SDK validation, which rejects it and replaces the result with incomplete fallback evidence. The result remains fail closed.");
  if(line===170) return useful("Failure records past the shared ceiling are dropped without marking the analysis incomplete. An oversized array of assertion errors becomes complete assertion-only evidence, which can incorrectly count as a killed mutant.","Overflow the shared failure record budget, require incomplete evidence, then verify the supported failure budget still retains complete assertion evidence and a corrected passing run stays clean.");
  if(line===174 && result.operator==="comparison") return detail("An error array exactly at the private event limit is rejected one event earlier. Both variants remain incomplete because this inventory also exceeds the much smaller shared failure record ceiling.");
  if(line===174 && result.operator==="boolean") return useful("Unsupported module or suite error metadata can be skipped without marking the run incomplete.","Supply invalid error metadata, require incomplete evidence, and retain a valid empty error array as the corrected passing control.");
  if(line===174 && before.endsWith("!Array.isArray(errors) ")) return useful("A non-array iterable error collection can pass the guard and be treated as complete runner metadata.","A module returning an empty Set for errors is incomplete, while the corrected empty array permits a clean complete result.");
  if(line===174) return detail("The individual error-array event check and aggregate reservation no longer run independently. Ordinary oversized arrays still exceed the shared failure ceiling and become incomplete. Custom array iterators could differ, so this is not a universal equivalence claim. Exact iteration accounting is an internal constraint rather than a proposed diagnostic test.");
  if(line===178) return detail("Module visits no longer contribute to the private aggregate event counter. The independent module limit remains, and the edit only changes available internal traversal capacity for a mixed inventory. No additional public arithmetic assertion is proposed.");
  if(line===179 && result.operator==="boolean") return useful("An unsupported module can be skipped while another valid module leaves complete evidence, hiding part of the reported run.","Collect a valid module plus a module with unavailable children metadata, require incomplete evidence, and retain the valid module alone as the corrected control.");
  if(line===179) return detail("A missing children or collection method reaches invocation and throws instead of the early guard. finalize catches that exception and publishes incomplete fallback evidence. The edit does not admit complete unsupported module data under the documented method contract.");
  if(line===182 && result.operator==="zeroOne") return useful("Suite visits stop consuming aggregate event capacity, removing the traversal bound for a suite iterator.","Use a finite oversized suite inventory, require incomplete evidence, and retain a normal suite inventory as the corrected control.");
  if(line===182 && result.operator==="boolean") return useful("A suite with unavailable error metadata can stop suite collection without marking the run incomplete, while ordinary tests still provide a complete result.","Use a suite missing its errors method alongside one valid test, require incomplete evidence, and correct the suite to an empty error array.");
  if(line===182) return detail("A missing suite errors method still throws into incomplete fallback publication, while reserve exhaustion independently marks unsupported. Collection can continue farther after exhaustion. This affects internal stopping behavior without demonstrating a false complete result.");
  if(line===186 && result.operator==="zeroOne") return detail("Test visits stop consuming the private aggregate event budget. The independent seen-test limit still bounds tests, so this changes mixed-inventory capacity without removing every traversal bound. No additional public arithmetic assertion is proposed.");
  if(line===186 && result.operator==="comparison" || line===186 && result.operator==="logical" && !before.includes("typeof test.id")) return useful("A passing test inventory beyond the reporter's seen-test limit can be accepted as complete.","Require an oversized unique passing-test inventory to remain incomplete, with a normal unique passing-test control.");
  if(line===186 && result.operator==="logical" && before.endsWith('typeof test.id !== "string" ')) return useful("A non-string test identifier can pass collection when it is otherwise a new passing test.","Use a passing test with invalid identity metadata, require incomplete evidence, and correct its ID to a string.");
  if(line===186 && result.operator==="logical") return useful("Duplicate passing test IDs can be counted twice without marking the result incomplete.","Collect duplicate passing test IDs, require incomplete evidence, and use distinct IDs as the corrected count control.");
  if(line===186) return useful("An invalid test entry can stop collection without marking the run incomplete. A previously collected valid passing test makes this appear complete.","Collect one valid passing test followed by unavailable result metadata, require incomplete evidence, and correct the missing result method.");
  if(line===192) return useful("A skipped test decrements the skipped count, producing invalid negative counters and conservative fallback for an otherwise valid run.","Run one passing test plus one skipped test, require complete evidence with the exact counts, and retain the passing-only control.");
  if(line===195) return useful("A failed test without error metadata can be marked complete with a runtime placeholder instead of incomplete.","Omit a failed test's error metadata, require incomplete evidence, and correct it with an actual assertion error.");
  if(line===196 && result.operator==="comparison") return detail("The edit rejects an array at the private per-test event boundary. Such an array also exceeds the shared failure record limit, so both variants remain incomplete.");
  if(line===196 && result.operator==="boolean") return useful("The changed assignment can restore supported after a failed test with missing errors already marked the run unsupported. Its runtime placeholder supplies the required failed test ID, so the SDK can accept complete:true.","Omit errors entirely on a failed test, require incomplete evidence, and correct it to a real assertion error array.");
  if(line===196) return detail("For ordinary error arrays, oversized data still fails the shared failure record ceiling or missing failed-ID validation. A custom non-array iterable with an invented length can differ. No extra assertion is proposed for that unsupported custom object, and this is not a universal equivalence claim.");
  if(line===198) return useful("A test in an unsupported state can be ignored while other valid passing tests leave complete evidence.","Collect a valid passing test plus a test with unknown state, require incomplete evidence, and correct that state to passed or skipped with the expected counts.");
  if(line===206 && result.operator==="equality") return useful("A throwing hook left in run state without an end callback loses complete hook failure classification.","Record a hook only at start with run state and actual errors, require hook failure evidence, and correct it to a passing completed hook.");
  if(line===206) return useful("A hook left in run state with no error metadata can be reported as a completed hook failure instead of incomplete metadata.","A started hook with no completion metadata stays incomplete, while a throwing started hook with errors is a complete hook failure and a completed passing hook adds no hook failure.");
  if(line===210) return useful("A replaced lifecycle method can escape the final identity check after a valid run and successful close.","Replace the close, logger, or wait method after their normal work has settled, require incomplete evidence, and preserve the same run without replacement as a clean control.");
  if(line===213 && result.operator==="comparison") return detail("The changed boundary rejects one error array earlier. Such an array also exceeds the shared failure-record ceiling, so ordinary arrays remain incomplete in either case.");
  if(line===213 && result.operator==="logical") return useful("A non-array iterable unhandled-error collection can be accepted as complete metadata.","Make getUnhandledErrors return an empty Set, require incomplete evidence, and correct it to an empty array for a clean complete run.");
  if(line===213) return useful("An unsupported or oversized unhandled-error inventory can be discarded without marking the run incomplete. A retained assertion failure can then appear complete and assertion-only.","Combine an assertion failure with oversized unhandled-error metadata, require incomplete evidence, and verify the corrected bounded unhandled-error inventory retains its separate failure kind.");
  if(line===233) return detail("The fallback result uses an invalid schema version and cannot be published. The reporter then forces contradictory raw status instead of preserving structured fallback metadata. This is weaker diagnostics on an already incomplete path, rather than false complete evidence.");
  if(line===234 && result.operator==="boolean") return detail("The fallback claims complete:true with infrastructureError, which the shared SDK rejects as contradictory. Publication then fails closed through the raw status guard. No complete fallback can be accepted.");
  if(line===234) return detail("The changed counter is part of conservative incomplete fallback metadata after normal collection failed. It changes that diagnostic placeholder, while the result remains incomplete and cannot kill a mutant. Requiring the exact placeholder would test fallback presentation rather than a false complete result.");
  return unresolved("This completed survivor has not yet received its individual source review.");
}

const rawRecords=fs.readdirSync(recordsDirectory).filter(file=>file.endsWith(".json")).map(file=>{
  const bytes=fs.readFileSync(path.join(recordsDirectory,file));const outer=JSON.parse(bytes);
  if(hash(outer.record)!==outer.checksum)throw new Error(`Checksum mismatch ${file}`);
  return {file,checksum:outer.checksum,bytesSha256:hash(bytes),record:JSON.parse(outer.record)};
});
rawRecords.sort((a,b)=>a.record.result.location.start-b.record.result.location.start);
const names=fs.readdirSync(root);
const survivors=rawRecords.filter(item=>item.record.result.outcome==="survived").map(item=>{
  const r=item.record.result;
  return {mutationId:r.mutationId,location:r.location,operator:r.operator,expected:r.expected,replacement:r.replacement,context:r.context,rawOutcome:r.outcome,recordFile:item.file,recordChecksum:item.checksum,cleanupComplete:item.record.cleanupComplete,...classify(r),directArtifacts:names.filter(name=>name.startsWith(`probe-${r.mutationId}-`)||name.startsWith(`test-proof-${r.mutationId}-`)).map(name=>path.join(root,name))};
});
const reportPath=path.join(root,"original-full-report.json");
const reportBytes=fs.existsSync(reportPath)?fs.readFileSync(reportPath):null;
const report=reportBytes?JSON.parse(reportBytes):null;
if(report){
  const expected=report.results.filter(r=>r.outcome==="survived");
  if(expected.length!==survivors.length || expected.some(r=>!survivors.find(s=>s.mutationId===r.mutationId)))throw new Error("Survivor set differs from authoritative report");
  for(const r of expected){const current=survivors.find(s=>s.mutationId===r.mutationId);if(current.expected!==r.expected||current.replacement!==r.replacement||JSON.stringify(current.location)!==JSON.stringify(r.location))throw new Error("Survivor metadata differs from authoritative report");}
}
const output={createdAt:new Date().toISOString(),scope:"Completed immutable checkpoints for the original five-control reporter profile. Raw outcomes are unchanged. Category decisions are source review and bounded authored probes, not a replacement mutation score.",completeRecordCount:rawRecords.length,expectedMutationCount:154,allExpectedRecordsAvailable:rawRecords.length===154,authoritativeReport:report?{file:reportPath,sha256:hash(reportBytes),complete:report.complete,summary:report.summary}:null,allSurvivorsMatchedAuthoritativeReport:!!report,outcomes:report?report.results.reduce((a,r)=>{a[r.outcome]=(a[r.outcome]??0)+1;return a},{}):rawRecords.reduce((a,item)=>{const outcome=item.record.result.outcome;a[outcome]=(a[outcome]??0)+1;return a},{}),classificationCounts:survivors.reduce((a,item)=>{a[item.classification]=(a[item.classification]??0)+1;return a},{}),sourceReporterSha256:hash(fs.readFileSync(path.join(sourceRoot,"sdk/mutator-vitest-reporter.ts"))),sourceProtocolSha256:hash(fs.readFileSync(path.join(sourceRoot,"sdk/mutator.ts"))),limitations:["Only finalized reusable records are read. Active worker files and journals are untouched.","Plain Node probes exercise authored lifecycle events. The original mutation run remains the actual installed Vitest comparison.","Matching outputs on sampled inputs do not prove equivalence. Equivalent decisions require source reasoning under the documented one-shot callback contract.","Internal diagnostic variants and exact private capacity boundaries do not automatically justify extra assertions.","Three timeouts remain in the original full report. They are not survivors or kills and no later probe replaces those recorded outcomes."],nonSurvivorIncompleteOutcomes:report?.results.filter(r=>r.outcome!=="survived"&&r.outcome!=="killed")??[],survivors};
const destination=path.join(root,report?"survivor-classification.final.json":"survivor-classification.interim.json");
fs.writeFileSync(destination,JSON.stringify(output,null,2));
console.log(JSON.stringify({destination,count:output.completeRecordCount,outcomes:output.outcomes,classifications:output.classificationCounts,unresolved:survivors.filter(r=>r.classification==="unresolved").map(r=>({id:r.mutationId,line:r.location.line,operator:r.operator,expected:r.expected,replacement:r.replacement,text:r.context.before+r.expected+r.context.after}))},null,2));
